on:
  push:
    branches: ['*']
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |        
          mkdir build && cd build
          cmake .. -G"Unix Makefiles"
          cmake --build . --target all
          ls -l 
          