permissions: write-all

on:
  push:
    branches: ['*']

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: update version
        env:
          GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
        run: |      
          whoami
            
          CURRENT_VERSION="$(grep '#define GREETER_VERSION_PATCH' version.h | cut -d' ' -f 3)"
          NEW_VERSION=$((CURRENT_VERSION + 1))
          sed -i "s/#define GREETER_VERSION_PATCH 1/#define GREETER_VERSION_PATCH ${NEW_VERSION}/" version.h
          grep '#define GREETER_VERSION_PATCH' version.h
          UPDATED_VERSION="$(grep '#define GREETER_VERSION_PATCH' version.h | cut -d' ' -f 3)"
          echo "Updated version is: ${UPDATED_VERSION}"

          sudo apt install git -y
           
          git remote set-url --push origin https://Dmitry1987:${GITHUB_TOKEN}@github.com/Dmitry1987/greeter

          git config --global user.name "Bot"  
          git config --global user.email bot@example.com   
          git commit -am "[BOT] version update"
          
          git push 


      # - name: push changes
      #   uses: devops-infra/action-commit-push@master
      #   with:
      #     github_token: "${{ secrets.GITHUB_TOKEN }}"
      #     add_timestamp: false
      #     commit_prefix: "[BOT]"
      #     commit_message: "version update"
      #     target_branch: "${{ github.ref_name }}"

