permissions: write-all

on:
  push:
    branches: ['*']

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: update version
        run: |        
          CURRENT_VERSION="$(grep '#define GREETER_VERSION_PATCH' version.h | cut -d' ' -f 3)"
          NEW_VERSION=$((CURRENT_VERSION + 1))
          sed -i "s/#define GREETER_VERSION_PATCH 1/#define GREETER_VERSION_PATCH ${NEW_VERSION}/" version.h
          grep '#define GREETER_VERSION_PATCH' version.h
          UPDATED_VERSION="$(grep '#define GREETER_VERSION_PATCH' version.h | cut -d' ' -f 3)"
          echo "Updated version is: ${UPDATED_VERSION}"

      - name: push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "[BOT]"
          commit_message: "version update"
          target_branch: "${{ github.ref_name }}"

